# Generated by Django 3.1.7 on 2021-04-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masjid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('target_amount', models.IntegerField(default=0)),
                ('raised_amount', models.IntegerField(default=0)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('userId', models.IntegerField(null=True)),
                ('detail', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('masjid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masjid_id', to='masjid.masjid')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='campaign_images')),
                ('video', models.FileField(null=True, upload_to='campaign_videos')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_data', to='campaign.campaign')),
            ],
        ),
    ]
