# Generated by Django 3.1.7 on 2021-04-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masjid_user', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('address', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SalahTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajar_azan', models.TimeField(null=True)),
                ('fajar_prayer', models.TimeField(null=True)),
                ('Dhuhr_azan', models.TimeField(null=True)),
                ('Dhuhr_prayer', models.TimeField(null=True)),
                ('Asr_azan', models.TimeField(null=True)),
                ('Asr_prayer', models.TimeField(null=True)),
                ('Maghrib_azan', models.TimeField(null=True)),
                ('Maghrib_prayer', models.TimeField(null=True)),
                ('Isha_azan', models.TimeField(null=True)),
                ('Isha_prayer', models.TimeField(null=True)),
                ('jummah_azan', models.TimeField(null=True)),
                ('jummah_prayer', models.TimeField(null=True)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masjid_prayers_time', to='masjid.masjid')),
            ],
        ),
    ]
